APP_HOST: "127.0.0.1"
APP_PORT: "7654"

READ_TIMEOUT: "15"
WRITE_TIMEOUT : "15"
IDLE_TIMEOUT: "60"

SHUTDOWN_TIMEOUT: "30"

#DB_POSTGRES_URL: "postgres://postgres:postgrespw@localhost:49153/Account"
#HOST_DB: "postgres"
#USER_DB: "postgres"
#PASSWORD_DB: "postgrespw"
#URL_DB: "localhost"
#NAME_DB: "Account"
#PORT_DB: "49153"

#DB_POSTGRES_URL: "postgres://zatrasz:rootroot@82.146.41.26:36526/Account?sslmode=disable"
HOST_DB: "postgres"
USER_DB: "zatrasz"
PASSWORD_DB: "rootroot"
URL_DB: "82.146.41.26"
NAME_DB: "Account"
PORT_DB: "36526"