APP_HOST: "127.0.0.1"
APP_PORT: "7654"

APP_CERT_PEM: "cert.pem"
APP_KEY_PEM: "key.pem"

READ_TIMEOUT: "15"
WRITE_TIMEOUT : "15"
IDLE_TIMEOUT: "60"

SHUTDOWN_TIMEOUT: "30"

#DB_POSTGRES_URL: "postgres://postgres:postgrespw@localhost:49153/Account?sslmode=disable"
HOST_DB: "postgres"
USER_DB: "postgres"
PASSWORD_DB: "postgrespw"
URL_DB: "localhost"
NAME_DB: "Account"
PORT_DB: "49153"