version: "3.8"

services:
  udo_chemistry:
    container_name: udo_chemistry
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7655:7654"
    environment:
      APP_HOST: "0.0.0.0" # Измените на нужный вам хост
      APP_PORT: "7654"
      READ_TIMEOUT: "15s"
      WRITE_TIMEOUT: "15s"
      IDLE_TIMEOUT: "60s"
      SHUTDOWN_TIMEOUT: "30s"